version: 2

models:
  - name: customer_master
    columns:
      - name: hubspot_company_id
        description: HubSpot uses owners to assign CRM objects (contacts, companies, and deals) to specific people in your organization.
        tests:
              - unique
  - name: companies
    columns:
      - name: hubspot_company_id
        description: This is a unique identifier for the customer within HubSpot
        tests:
              - not_null
              - unique
  - name: pipelines
    columns:
      - name: pipelineid
        description: This is a unique identifier for the pipe line
        tests:
              - not_null
  - name: pipeline_stages
    columns:
      - name: stageid
        description: This is a unique identifier for the pipe line
        tests:
              - not_null
  - name: deals
    columns:
      - name: hubspot_owner_id
        description: HubSpot uses owners to assign CRM objects (contacts, companies, and deals) to specific people in your organization.
        tests:
      - name: deadstage_id
        description: This is a unique identifier for the deal stage
        tests:
      - name: deal_id
        description: This is a unique identifier for the corrosponding deal
        tests:
              - not_null
              - unique
  - name: deals_labelled
    columns:
      - name: deal_id
        description: This is a unique identifier for the pipe line
        tests:
              - not_null
              - unique
  - name: hubspot_companies
    columns:
      - name: hubspot_owner_id
        description: HubSpot uses owners to assign CRM objects (contacts, companies, and deals) to specific people in your organization.
  - name: owners
    columns:
      - name: ownerid
        description: HubSpot uses owners to assign CRM objects (contacts, companies, and deals) to specific people in your organization.
        tests:
              - not_null
              - unique
