version: 2

models:
  - name: email_campaign_content_links_dim
    tests:
        - unique:
              column_name: "CONCAT(campaign_id,url)"
        - not_null:
               column_name: campaign_id
        - relationships:
               column_name: campaign_id
               to: ref('email_campaigns_dim')
               field: campaign_id
  - name: email_campaigns_dim
    columns:
      - name: campaign_id
        description: This is a unique identifier for the campaign
        tests:
              - not_null
              - unique
  - name: email_contacts_dim
    tests:
        - unique:
               column_name: "CONCAT(email_id,'-', STRING(valid_to))"
        - not_null:
               column_name: email_id
               column_name: valid_from
  - name: email_list_membership_fact
    tests:
        - unique:
               column_name: "CONCAT(list_member_id, STRING(valid_from))"
        - not_null:
               column_name: list_member_id
               column_name: email_id
               column_name: valid_from
  - name: email_lists_dim
    columns:
      - name: list_id
        description: The unique identifier for each list.
        tests:
              - not_null
              - unique
  - name: email_segment_membership_fact
    tests:
        - unique:
               column_name: "CONCAT(list_member_id,'-',CAST(segment_id as STRING), STRING(valid_from))"
        - not_null:
               column_name: list_member_id
               column_name: email_id
               column_name: segment_id
               column_name: valid_from
  - name: email_segments_dim
    tests:
        - unique:
               column_name: segment_id
        - not_null:
               column_name: segment_id
  - name: email_send_fact
    tests:
        - unique:
               column_name: send_id
        - not_null:
               column_name: send_id
               column_name: campaign_id
               column_name: list_id
  - name: email_response_fact
    tests:
        - unique:
               column_name: event_id
        - not_null:
               column_name: send_id
               column_name: campaign_id
               column_name: list_id
               column_name: event_at
