SELECT
  properties.founded_year.value hubspot_founded_year,
  properties.first_deal_created_date.value hubspot_first_deal_created_date,
  properties.hs_sales_email_last_replied.value hubspot_sales_email_last_replied,
  properties.linkedin_company_page.value hubspot_linkedin_company_page,
  properties.twitterhandle.value hubspot_twitterhandle,
  properties.numberofemployees.value hubspot_numberofemployees,
  properties.country.value hubspot_country,
  properties.total_money_raised.value hubspot_total_money_raised,
  properties.city.value hubspot_city,
  properties.total_revenue.value hubspot_total_revenue,
  properties.hs_analytics_num_page_views.value hubspot_num_page_views,
  properties.bi_technology_type.value hubspot_bi_technology_type,
  properties.annualrevenue.value hubspot_annual_revenue,
  properties.num_contacted_notes.value hubspot_num_contacted_notes,
  properties.web_technologies.value hubspot_web_technologies,
  properties.website.value hubspot_website,
  properties.hubspot_owner_id.value hubspot_owner_id,
  properties.facebook_company_page.value hubspot_facebook_company_page,
  properties.industry.value hubspot_industry,
  properties.recent_deal_amount.value hubspot_recent_deal_amount,
  properties.address2.value hubspot_address2,
  properties.linkedinbio.value hubspot_linkedin_bio,
  replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(properties.name.value,', Ltd.',''),', Inc','')
  ,' LLC',''),' Cosmetics',''),' Ltd.',''),' Inc',''),' Digital Limited',''),' Group',''),' Consulting',''),' Computing.',''),'SEED Beauty','Colourpop'),'Digital Staff Solutions Ltd','Florence'),'Resolver','Resolving Group Ltd') hubspot_company_name,
  properties.is_public.value hubspot_is_public,
  properties.notes_last_updated.value hubspot_notes_last_updated,
  properties.num_associated_deals.value hubspot_num_associated_deals,
  properties.address.value hubspot_address,
  properties.domain.value hubspot_domain,
  properties.closedate.value hubspot_closedate,
  properties.first_contact_createdate.value hubspot_first_contact_createdate,
  properties.createdate.value hubspot_created_date,
  properties.type.value hubspot_type,
  properties.phone.value hubspot_phone,
  properties.state.value hubspot_state,
  properties.lifecyclestage.value hubspot_lifecycle_stage,
  properties.notes_last_contacted.value hubspot_notes_last_contacted,
  properties.hubspot_owner_assigneddate.value hubspot_owner_assigned_date,
  properties.num_notes.value hubspot_num_notes,
  properties.recent_deal_close_date.value hubspot_recent_deal_close_date,
  properties.zip.value hubspot_zip,
  properties.description.value hubspot_description,
  properties.num_associated_contacts.value hubspot_num_associated_contacts,
  companyid as hubspot_company_id
FROM
  {{ ref('hubspot_base_companies') }}
  group by 1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43
