SELECT
  *
FROM (
  SELECT
    properties.email.value email,
    properties.lastname.value lastname,
    properties.hs_searchable_calculated_phone_number.value hs_searchable_calculated_phone_number,
    properties.first_deal_created_date.value first_deal_created_date,
    properties.hs_sales_email_last_replied.value hs_sales_email_last_replied,
    properties.twitterhandle.value twitterhandle,
    properties.country.value country,
    properties.hs_email_domain.value hs_email_domain,
    properties.hubspotscore.value hubspotscore,
    properties.city.value city,
    properties.company.value company,
    properties.total_revenue.value total_revenue,
    properties.hs_analytics_num_page_views.value hs_analytics_num_page_views,
    properties.hs_sales_email_last_opened.value hs_sales_email_last_opened,
    properties.hs_lead_status.value hs_lead_status,
    properties.hs_searchable_calculated_mobile_number.value hs_searchable_calculated_mobile_number,
    properties.website.value website,
    properties.num_contacted_notes.value num_contacted_notes,
    properties.associatedcompanyid.value associatedcompanyid,
    properties.mobilephone.value mobilephone,
    properties.industry.value industry,
    properties.recent_deal_amount.value recent_deal_amount,
    properties.lastmodifieddate.value lastmodifieddate,
    properties.hs_calculated_phone_number_country_code.value hs_calculated_phone_number_country_code,
    properties.hs_email_optout.value hs_email_optout,
    properties.num_associated_deals.value num_associated_deals,
    properties.address.value address,
    properties.hs_lifecyclestage_customer_date.value hs_lifecyclestage_customer_date,
    properties.hs_calculated_phone_number.value hs_calculated_phone_number,
    properties.createdate.value createdate,
    properties.phone.value phone,
    properties.recruitment_stage.value recruitment_stage,
    properties.state.value state,
    properties.lifecyclestage.value lifecyclestage,
    properties.salutation.value salutation,
    properties.hs_analytics_revenue.value hs_analytics_revenue,
    properties.jobtitle.value jobtitle,
    properties.firstname.value firstname,
    properties.recent_deal_close_date.value recent_deal_close_date,
    properties.zip.value zip,
    properties.recruitment_prospect.value recruitment_prospect,
    properties.hs_is_contact.value hs_is_contact,
    properties.ip_zipcode.value ip_zipcode,
    properties.ip_city.value ip_city,
    properties.ip_country_code.value ip_country_code,
    properties.hs_ip_timezone.value hs_ip_timezone,
    properties.ip_state.value ip_state,
    properties.ip_country.value ip_country,
    properties.hs_analytics_last_visit_timestamp.value hs_analytics_last_visit_timestamp,
    properties.ip_state_code.value ip_state_code,
    canonical_vid,
    _sdc_sequence,
    _sdc_received_at,
    MAX(_sdc_sequence) OVER (PARTITION BY canonical_vid ORDER BY _sdc_received_at RANGE BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING ) AS max_sdc_sdc_sequence,
    is_contact
  FROM
    {{ ref('hubspot_base_contacts') }} )
WHERE
  _sdc_sequence = max_sdc_sdc_sequence
  AND email IS NOT NULL
